.\" Manpage for iptables-firewall by user <user@host>

.TH "iptables-firewall" "5" "2013-12-04" "user" "iptables-firewall"

.SH NAME

iptables-firewall - Einstellungen für das Skript iptables-firewall

.SH DESCRIPTION

Its a POSIX shell fragment!

Nach dem bearbeiten muss update-iptables-firewall(8) ausgeführt werden,
um die Änderungen zu übernehmen.

.SH FILES

.SS /etc/iptables-firewall/config

Einstellungen.

.SH SEE ALSO

.BR update-iptables-firewall(8)

