.\" Manpage for iptables-firewall by nobody <nobody>

.TH "iptables-firewall" "5" "2013-12-04" "nobody" "iptables-firewall"

.SH NAME

iptables-firewall - Einstellungen für iptables-firewall

.SH DESCRIPTION

Absoluter Pfad: /etc/iptables-firewall/iptables-firewall

Its a POSIX shell fragment!

Nach dem bearbeiten muss update-iptables-firewall(8) ausgeführt werden,
um die Änderungen zu übernehmen.

